repos:
  # lint yaml, line and whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # lint the dockerfiles
  - repo: https://github.com/hadolint/hadolint
    rev: c3dc18df7a501f02a560a2cc7ba3c69a85ca01d3  # frozen: v2.13.1-beta
    hooks:
      - id: hadolint

  # prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "f12edd9c7be1c20cfa42420fd0e6df71e42b51ea"  # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [file, bash, sh, javascript, jsx, ts, tsx]
        additional_dependencies:
          - prettier@2.5.1
        exclude: ^(Dockerfile*)

  - repo: https://github.com/codespell-project/codespell.git
    rev: "63c8f8312b7559622c0d82815639671ae42132ac"  # frozen: v2.4.1
    hooks:
      - id: codespell
        types: [text]
        args: [--ignore-words=.dictionary.txt]
        exclude: ^(Dockerfile*)

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95  # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 54da05914997e6b04e4db33ed6757d744984c68b  # frozen: 0.33.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a89e69d5772bdee97db1a6a898467b686e  # frozen: v1.0
    hooks:
      - id: fmt
      - id: cargo-check

    # lint python formatting
  - repo: https://github.com/psf/black
    rev: 8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b  # frozen: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: "d93590f5be797aabb60e3b09f2f52dddb02f349f"  # frozen: 7.3.0
    hooks:
      - id: flake8
        args: ["--extend-ignore=W503,W504,E501"]
