name: Update pre-commit hooks

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

jobs:
  pre-commit-update:
    runs-on: ubuntu-22.04
    name: Updates
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Update pre-commit hooks
        uses: brokenpip3/action-pre-commit-update@0.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
